# Created with: conda env export --from-history > environment.yml
name: streamlit
channels:
  - plotly  # manually added
  - defaults
  - conda-forge
dependencies:
  - streamlit
  - pandas
#  - ca-certificates
#  - certifi
#  - openssl
  - matplotlib
  - plotly

